Update Terraform "workspace does not exist" regex
Terraform 1.0.10 changed the error message returned when called with the `-input=false` flag is passed. Now, it will return an error message like the following:

```
Error: Currently selected workspace "foo" does not exist
```